/*
 * Aetherium Framework — generator for the zero-config AetheriumMod bootstrap source.
 * Copyright (C) 2026 RedstoneTeam. Licensed under AGPL-3.0-or-later.
 * See <https://www.gnu.org/licenses/>.
 */
package org.aetherium.datagen;

import java.util.List;

/**
 * Emits the Java source of the generated {@link org.aetherium.core.mod.AetheriumMod} that statically
 * dispatches every {@code @AetheriumInit} method in resolved order.
 *
 * <p>EN: Pure string generation (no {@code Filer}, no compiler types) so it is unit-testable in isolation.
 * The produced class implements {@code AetheriumMod} and, in {@code onInitialize}, calls each init by
 * <em>direct static invocation</em> — there is no reflection, no lookup, no map; the call sites are fixed
 * at compile time. The class name embeds the (sanitized) mod id so two Aetherium mods on one classpath
 * never collide. The matching {@code META-INF/services} line is produced by {@link #serviceEntry(String)}.
 * RU: Чистая генерация строки (без {@code Filer} и типов компилятора), поэтому тестируется изолированно.
 * Класс реализует {@code AetheriumMod} и в {@code onInitialize} вызывает каждый init <em>прямым
 * статическим вызовом</em> — без рефлексии, поиска и карт; точки вызова фиксированы на этапе компиляции.
 * Имя класса включает (санированный) mod id, чтобы два мода на одном classpath не конфликтовали.
 */
public final class InitSourceWriter {

    /** The package the generated bootstrap is emitted into. */
    public static final String GENERATED_PACKAGE = "org.aetherium.generated";

    private InitSourceWriter() {
    }

    /** The simple class name generated for {@code modId} (sanitized to a legal Java identifier). */
    public static String className(String modId) {
        return "AetheriumGeneratedInit_" + sanitize(modId);
    }

    /** The fully-qualified name of the generated bootstrap for {@code modId}. */
    public static String qualifiedName(String modId) {
        return GENERATED_PACKAGE + "." + className(modId);
    }

    /** The {@code META-INF/services/org.aetherium.core.mod.AetheriumMod} line for this generated class. */
    public static String serviceEntry(String modId) {
        return qualifiedName(modId);
    }

    /**
     * EN: Generate the full source of the bootstrap for {@code modId} from the already-ordered inits.
     * RU: Сгенерировать полный исходник bootstrap для {@code modId} из уже упорядоченных инициализаторов.
     */
    public static String generate(String modId, List<InitMethod> orderedInits) {
        String cls = className(modId);
        StringBuilder sb = new StringBuilder(512);
        sb.append("// Generated by Aetherium @AetheriumInit processor — do not edit.\n");
        sb.append("package ").append(GENERATED_PACKAGE).append(";\n\n");
        sb.append("/** Zero-config entrypoint for mod '").append(modId)
                .append("': statically dispatches every @AetheriumInit method in DAG order. */\n");
        sb.append("public final class ").append(cls)
                .append(" implements org.aetherium.core.mod.AetheriumMod {\n\n");
        sb.append("    @Override\n");
        sb.append("    public void onInitialize(org.aetherium.core.mod.AetheriumContext context) {\n");
        if (orderedInits.isEmpty()) {
            sb.append("        // no @AetheriumInit methods were declared\n");
        }
        for (InitMethod m : orderedInits) {
            if (m.sideGated()) {
                // gate a side-declared init on the JVM's physical side. A CLIENT init never runs on a
                // dedicated server; SERVER/BOTH run wherever they are safe (see Side.activeOn).
                sb.append("        if (context.runsOnSide(org.aetherium.core.mod.Side.").append(m.side())
                        .append(")) {\n");
                sb.append("            ").append(m.invocation("context"))
                        .append("   // ").append(m.id()).append(" [").append(m.side()).append("]\n");
                sb.append("        }\n");
            } else {
                sb.append("        ").append(m.invocation("context"))
                        .append("   // ").append(m.id()).append('\n');
            }
        }
        sb.append("    }\n\n");
        sb.append("    @Override\n");
        sb.append("    public String id() {\n");
        sb.append("        return \"").append(escape(modId)).append("\";\n");
        sb.append("    }\n");
        sb.append("}\n");
        return sb.toString();
    }

    /** Turn an arbitrary mod id into a legal Java identifier fragment for the class name. */
    static String sanitize(String modId) {
        if (modId == null || modId.isBlank()) {
            return "Default";
        }
        StringBuilder out = new StringBuilder(modId.length());
        for (int i = 0; i < modId.length(); i++) {
            char c = modId.charAt(i);
            boolean ok = (i == 0) ? Character.isJavaIdentifierStart(c) : Character.isJavaIdentifierPart(c);
            out.append(ok ? c : '_');
        }
        return out.length() == 0 ? "Default" : out.toString();
    }

    private static String escape(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
