/*
 * Aetherium Framework — mod project scaffolder.
 * Copyright (C) 2026 RedstoneTeam. Licensed under AGPL-3.0-or-later.
 * See <https://www.gnu.org/licenses/>.
 */
package org.aetherium.cli.scaffold;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Scaffolds a fully-configured, Aetherium-compatible mod project — the "zero boilerplate" DX.
 *
 * <p>EN: {@code aetherium init my-mod} produces a ready-to-build Gradle project: build scripts,
 * NeoForge mod metadata, an example mod that already uses the Aetherium ASM + Native (ComputePipeline)
 * APIs, an AGPL-3.0 LICENSE, and per-file AGPL headers (so generated code respects the framework's
 * copyleft). The developer writes zero infrastructure.
 *
 * <p>RU: {@code aetherium init my-mod} создаёт готовый к сборке проект Gradle: скрипты сборки,
 * метаданные мода NeoForge, пример мода, уже использующего API Aetherium ASM + Native
 * (ComputePipeline), лицензию AGPL-3.0 и AGPL-заголовки в каждом файле (чтобы сгенерированный код
 * уважал копилефт фреймворка). Разработчик не пишет инфраструктуру.
 */
public final class ModScaffolder {

    private final String rawName;
    private final String modId;
    private final String packageName;
    private final String mainClass;

    public ModScaffolder(String rawName) {
        this.rawName = rawName;
        this.modId = sanitizeModId(rawName);
        this.packageName = "org.example." + modId.replace('-', '_').replace('.', '_');
        this.mainClass = toPascalCase(modId) + "Mod";
    }

    /** Files created, returned for reporting. Throws {@link IOException} on I/O failure only. */
    public List<Path> scaffold(Path targetDir) throws IOException {
        if (Files.exists(targetDir) && Files.list(targetDir).findAny().isPresent()) {
            throw new IOException("Target directory exists and is not empty: " + targetDir);
        }
        List<Path> created = new ArrayList<>();
        String pkgPath = packageName.replace('.', '/');
        Path javaDir = targetDir.resolve("src/main/java/" + pkgPath);
        Path resDir = targetDir.resolve("src/main/resources/META-INF");

        created.add(write(targetDir.resolve("settings.gradle.kts"), settingsGradle()));
        created.add(write(targetDir.resolve("build.gradle.kts"), buildGradle()));
        created.add(write(targetDir.resolve("gradle.properties"), gradleProperties()));
        created.add(write(targetDir.resolve(".gitignore"), gitignore()));
        created.add(write(targetDir.resolve("LICENSE"), licenseNotice()));
        created.add(write(targetDir.resolve("README.md"), readme()));
        created.add(write(javaDir.resolve(mainClass + ".java"), exampleMod()));
        created.add(write(resDir.resolve("neoforge.mods.toml"), modsToml()));
        return created;
    }

    public String modId() {
        return modId;
    }

    public String mainClass() {
        return mainClass;
    }

    public String packageName() {
        return packageName;
    }

    private static Path write(Path file, String content) throws IOException {
        Files.createDirectories(file.getParent());
        Files.writeString(file, content);
        return file;
    }

    // --- templates -------------------------------------------------------------------------------

    private String agplHeader(String what) {
        return """
                /*
                 * %s — %s.
                 * Copyright (C) 2026 %s authors.
                 *
                 * This program is free software: you can redistribute it and/or modify it under the
                 * terms of the GNU Affero General Public License as published by the Free Software
                 * Foundation, either version 3 of the License, or (at your option) any later version.
                 * See <https://www.gnu.org/licenses/>.
                 *
                 * NOTE: Aetherium is AGPL-3.0. Mods that build on it and are offered to users over a
                 * network must also provide their complete corresponding source under AGPL-3.0.
                 */
                """.formatted(rawName, what, rawName);
    }

    private String settingsGradle() {
        return "rootProject.name = \"" + modId + "\"\n";
    }

    private String buildGradle() {
        return """
                // %s — Aetherium-compatible mod (generated by `aetherium init`).
                plugins {
                    `java-library`
                }

                group = "org.example"
                version = "0.1.0"

                repositories {
                    mavenCentral()
                    mavenLocal() // Aetherium artifacts (publish them locally with `publishToMavenLocal`)
                    maven("https://maven.neoforged.net/releases")
                }

                dependencies {
                    // The Aetherium API surface — write against these, never against a specific loader.
                    implementation("org.aetherium:aetherium-core:0.1.0-SNAPSHOT")
                    implementation("org.aetherium:aetherium-bytecode:0.1.0-SNAPSHOT")
                    implementation("org.aetherium:aetherium-native:0.1.0-SNAPSHOT")
                }

                java {
                    toolchain { languageVersion.set(JavaLanguageVersion.of(21)) }
                }

                tasks.withType<JavaCompile>().configureEach {
                    options.release.set(21)
                    options.compilerArgs.addAll(listOf("--enable-preview"))
                }
                """.formatted(rawName);
    }

    private String gradleProperties() {
        return "org.gradle.java.installations.auto-download=false\n";
    }

    private String gitignore() {
        return """
                build/
                .gradle/
                *.class
                .idea/
                """;
    }

    private String exampleMod() {
        return agplHeader("example Aetherium mod") + """
                package %s;

                import org.aetherium.core.compute.ComputePipeline;
                import org.aetherium.core.compute.ComputePipeline.ComputeJob;

                import java.lang.foreign.Arena;
                import java.lang.foreign.MemorySegment;
                import java.lang.foreign.ValueLayout;

                /**
                 * %s — a minimal Aetherium mod.
                 *
                 * Zero boilerplate: you receive a ready {@link ComputePipeline} from the framework and
                 * submit work. You never write JNI, FFM, or ASM glue — Aetherium handles the loader,
                 * the bytecode transformation, and the native bridge for you.
                 */
                public final class %s {

                    /** Called by Aetherium during mod initialization (loader-agnostic). */
                    public void onInitialize(ComputePipeline pipeline) {
                        try (Arena arena = Arena.ofConfined()) {
                            MemorySegment input = arena.allocate(4);
                            input.set(ValueLayout.JAVA_BYTE, 0, (byte) 21);
                            pipeline.submit(new ComputeJob("example-kernel", input, 4))
                                    .thenAccept(out ->
                                            System.out.println("[%s] compute result byte[0] = "
                                                    + out.get(ValueLayout.JAVA_BYTE, 0)));
                        }
                    }
                }
                """.formatted(packageName, rawName, mainClass, modId);
    }

    private String modsToml() {
        return """
                # %s — NeoForge mod descriptor (generated by `aetherium init`).
                modLoader = "javafml"
                loaderVersion = "[4,)"
                license = "AGPL-3.0-or-later"

                [[mods]]
                modId = "%s"
                version = "0.1.0"
                displayName = "%s"
                description = '''
                An Aetherium-powered mod. Runs on any supported loader via the Aetherium meta-layer.
                '''

                [[dependencies.%s]]
                modId = "neoforge"
                type = "required"
                versionRange = "[21.1.93,)"
                ordering = "NONE"
                side = "BOTH"
                """.formatted(rawName, modId, rawName, modId);
    }

    private String licenseNotice() {
        return """
                %s is licensed under the GNU Affero General Public License v3.0 (AGPL-3.0-or-later).

                This project depends on the Aetherium Framework, which is AGPL-3.0. Per the AGPL, if you
                modify this software and make it available to users over a network (e.g. a game server),
                you must provide the complete corresponding source under the same license.

                Obtain the full license text at <https://www.gnu.org/licenses/agpl-3.0.txt> and place it
                in this file before distribution.
                """.formatted(rawName);
    }

    private String readme() {
        return """
                # %s

                An Aetherium-compatible mod, scaffolded by `aetherium init`.

                ## Build
                ```bash
                ./gradlew build   # produces a drop-in mod jar
                ```

                ## License
                AGPL-3.0-or-later (inherited from the Aetherium Framework). See `LICENSE`.

                ---

                Мод, совместимый с Aetherium, сгенерированный `aetherium init`.
                Лицензия: AGPL-3.0-or-later (унаследовано от Aetherium). См. `LICENSE`.
                """.formatted(rawName);
    }

    // --- helpers ---------------------------------------------------------------------------------

    static String sanitizeModId(String raw) {
        String lower = raw.toLowerCase(Locale.ROOT).trim();
        StringBuilder sb = new StringBuilder(lower.length());
        for (int i = 0; i < lower.length(); i++) {
            char c = lower.charAt(i);
            if ((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9')) {
                sb.append(c);
            } else if (c == '-' || c == '_' || c == ' ' || c == '.') {
                sb.append('-');
            }
            // drop anything else
        }
        String cleaned = sb.toString().replaceAll("-+", "-").replaceAll("^-|-$", "");
        if (cleaned.isEmpty() || !Character.isLetter(cleaned.charAt(0))) {
            cleaned = "mod" + (cleaned.isEmpty() ? "" : "-" + cleaned);
        }
        return cleaned;
    }

    static String toPascalCase(String modId) {
        StringBuilder sb = new StringBuilder();
        for (String part : modId.split("[-_.]")) {
            if (!part.isEmpty()) {
                sb.append(Character.toUpperCase(part.charAt(0))).append(part.substring(1));
            }
        }
        return sb.isEmpty() ? "Example" : sb.toString();
    }
}
